APPLICATION ?= opserver
ENVIRONMENT ?= dev
INSTANCE_TYPE ?= t3.medium
VERSION := $(shell date '+%Y%m%d%H%M%S')

prereq:
	APPLICATION=${APPLICATION} \
	ENVIRONMENT=${ENVIRONMENT} \
	scripts/deploy-prereq.sh

validate-image:
	OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES \
	ACTION=validate \
	APPLICATION=${APPLICATION} \
	ENVIRONMENT=${ENVIRONMENT} \
	INSTANCE_TYPE=${INSTANCE_TYPE} \
	VERSION=${VERSION} \
	scripts/image.sh

bake-image:
	OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES \
	ACTION=build \
	APPLICATION=${APPLICATION} \
	ENVIRONMENT=${ENVIRONMENT} \
	INSTANCE_TYPE=${INSTANCE_TYPE} \
	VERSION=${VERSION} \
	scripts/image.sh
